[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gluster/glusterd2"
  branch = "master"
