[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/gluster/glusterd2"
  branch = "master"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.3"
